# Generated by Django 3.0.8 on 2020-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodalOfficer',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
