# Generated by Django 3.0.6 on 2020-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200729_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.CharField(max_length=20)),
                ('in_sub', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('caseno', models.CharField(max_length=50)),
                ('lcno', models.CharField(max_length=50)),
                ('ad_na', models.CharField(max_length=50)),
                ('casetitle', models.CharField(max_length=20)),
                ('casetype', models.CharField(max_length=20)),
                ('in_particulars', models.CharField(max_length=500)),
                ('in_total', models.IntegerField()),
                ('in_due', models.IntegerField()),
            ],
        ),
    ]
