# Generated by Django 3.0.8 on 2020-07-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_lawyer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lawyer',
            new_name='Advocate',
        ),
    ]
