# Generated by Django 3.0.8 on 2020-07-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_invoice'),
        ('backend', '0004_auto_20200730_1850'),
    ]

    operations = [
    ]
