# Generated by Django 3.0.8 on 2020-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_merge_20200731_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('case_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('lastHearing', models.DateField()),
                ('conclusion', models.CharField(max_length=50)),
                ('nextHearing', models.DateField()),
            ],
        ),
    ]
