# Generated by Django 3.0.8 on 2020-07-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200731_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCases',
            fields=[
                ('type_of_court', models.CharField(choices=[('Supreme Court', 'Supreme Court'), ('Junior Division Court', 'Junior Division Court'), ('Senior Division Court', 'Senior Division Court'), ('Consumer Court', 'Consumer Court'), ('Family Court', 'Family Court'), ('Sale Tax Tribunal', 'Sale Tax Tribunal'), ('Additional District Judge Court', 'Additional District Judge Court')], default='Supreme Court', max_length=50)),
                ('type_of_case', models.CharField(choices=[('Criminal Case', 'Criminal Case'), ('Property Case', 'Property Case'), ('Divorse Case', 'Divorse Case'), ('Civil Case', 'Civil Case')], max_length=50)),
                ('case_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('case_registration_date', models.CharField(max_length=50)),
                ('court_name', models.CharField(choices=[('BMC High Court', 'BMC High Court'), ('Junior Court', 'Junior Court'), ('NyayMandir', 'NyayMandir'), ('Lal Court', 'Lal Court')], max_length=50)),
                ('subject_matter', models.CharField(choices=[('Cheque Bounce Matter', 'Cheque Bounce Matter'), ('Unauthorized Construction', 'Unauthorized Construction'), ('Property Tax Matter', 'Property Tax Matter'), ('Estabhlishment Matter', 'Estabhlishment Matter'), ('Advertisement Matter', 'Advertisement Matter'), ('A.F.A Act', 'A.F.A Act'), ('Against Disimisal 106 Appointment Matter', 'Against Disimisal 106 Appointment Matter'), ('Public Health Related Matter', 'Public Health Related Matter')], max_length=50)),
                ('lc_number', models.CharField(max_length=50, unique=True)),
                ('section', models.CharField(choices=[('148', '148'), ('152', '152'), ('160', '160'), ('180', '180')], max_length=50)),
                ('previous_casenumber', models.CharField(max_length=50)),
                ('case_receiving_date', models.CharField(max_length=50)),
                ('appearance_date_respondent', models.CharField(max_length=50)),
                ('pwc_duedate', models.CharField(max_length=50)),
                ('duedate_filing', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('prayer', models.CharField(max_length=50)),
                ('filedby_corporation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('stamp_no', models.CharField(max_length=50)),
                ('first_apperance_petitioner', models.CharField(max_length=50)),
                ('petitioner_counsel_name', models.CharField(max_length=50)),
                ('represented_by_coordinator', models.CharField(max_length=50)),
                ('next_hearing_date', models.CharField(default='xx/xx/2020', max_length=50)),
                ('app_isemployee', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('app_name', models.CharField(max_length=100)),
                ('app_address', models.CharField(max_length=200)),
                ('app_contact', models.IntegerField()),
                ('app_dept', models.CharField(choices=[('Central Railway', 'Central Railway'), ('Ministry of Agriculture', 'Ministry of Agriculture'), ('Urban Development(UD)', 'Urban Development(UD)'), ('Forest Department', 'Forest Department'), ('Department of Home', 'Department of Home'), ('Ministry of Textile', 'Ministry of Textile')], max_length=50)),
                ('res_isemployee', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('res_name', models.CharField(max_length=100)),
                ('res_address', models.CharField(max_length=200)),
                ('res_contact', models.IntegerField()),
                ('res_dept', models.CharField(choices=[('Central Railway', 'Central Railway'), ('Ministry of Agriculture', 'Ministry of Agriculture'), ('Urban Development(UD)', 'Urban Development(UD)'), ('Forest Department', 'Forest Department'), ('Department of Home', 'Department of Home'), ('Ministry of Textile', 'Ministry of Textile')], max_length=50)),
                ('ass_isprimarydept', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('ass_dept', models.CharField(max_length=50)),
                ('ass_assignedto', models.CharField(max_length=50)),
                ('ass_assignedon', models.CharField(max_length=50)),
                ('ass_date_receipt_pwc', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=500)),
                ('standing_counsel', models.CharField(max_length=50)),
                ('standingcounsel_assignedon', models.CharField(max_length=50)),
                ('vakalatnama_filingdate', models.CharField(max_length=50)),
                ('date_of_filing_writtenstatement', models.CharField(max_length=50)),
                ('standing_counsel_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
