# Generated by Django 3.0.8 on 2020-08-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_addcases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hearing',
        ),
    ]
