# Generated by Django 3.0.8 on 2020-08-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_delete_hearing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('lastHearing', models.DateField()),
                ('conclusion', models.CharField(max_length=150)),
                ('nextHearing', models.DateField()),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
