# Generated by Django 3.0.8 on 2020-08-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_hearing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
