# Generated by Django 3.0.8 on 2020-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='lastHearing',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='nextHearing',
            field=models.CharField(max_length=30),
        ),
    ]
