# Generated by Django 3.0.8 on 2020-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200802_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('userID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('typee', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='NodalOfficer',
        ),
    ]
