# Generated by Django 3.0.8 on 2020-08-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200802_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hearing',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Running', 'Running')], default='Closed', max_length=20),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='case_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='conclusion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='nextHearing',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='in_date',
            field=models.CharField(max_length=50),
        ),
    ]
